package com.bms.transaction.enums;


public enum LedgerType {
	PENDING,
	DEBIT_REQUESTED,
	DEBIT_SUCCESS,
	DEBIT_FAILED,
	CREDIT_REQUESTED,
	CREDIT_SUCCESS,
	CREDIT_FAILED,
	COMPENSATION_DEBIT,
	COMPENSATION_CREDIT,
	COMPLETED,
	FAILED
}