package com.bms.transaction.enums;

public enum TransactionStatus {
    PENDING,
    COMPLETED,
    FAILED,
    REFUND,
	PROCESSING,
	DEBIT_COMPLETED,
	COMPENSATION,
	PERMANENT_FAILURE,
	COMPENSATION_COMPLETED,
	COMPENSATION_FAILED,
	COMPENSATED, DEBIT_PENDING, CREDIT_PENDING, ROLLED_BACK
}