package com.bms.loan.enums;

public enum LoanStatus {
    APPLIED,
    UNDER_REVIEW,
    DOCUMENTS_SUBMITTED,
    APPROVED,
    REJECTED,
    DISBURSED,
    CLOSED,
    OVERDUE, VERIFIED, VERIFICATION_PENDING, EVALUATED
}
