package com.bms.notification;

public enum TransactionStatus {
    PENDING,
    COMPLETED,
    FAILED,
    REFUND,
	PROCESSING,
	DEBIT_COMPLETED,
	COMPENSATION,
	PERMANENT_FAILURE,
	COMPENSATION_COMPLETED,
	COMPENSATION_FAILED,
	COMPENSATED, ROLLED_BACK
}